
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class AppTokoJFrame extends javax.swing.JFrame {
cPelanggan plg[];
 cBarang brg[]; cPembelian pbl[];
 int jplg, jbrg, jpbl; //indeks array
 int mplg, mbrg, mpbl; //nilai maksimal array
 //constructor
 public AppTokoJFrame() {
 plg = new cPelanggan[3];
brg = new cBarang[5];
 pbl = new cPembelian[15];
 jplg=jbrg=jpbl=0;
 mplg=3; mbrg=5; mpbl=15;
   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextIdPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextNamaPelanggan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextAlamatPelanggan = new javax.swing.JTextField();
        TambahPelanggan = new java.awt.Button();
        UbahPelanggan = new java.awt.Button();
        HapusPelanggan = new java.awt.Button();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextKodeBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextNamaBarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextHargaBarang = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TambahBarang = new java.awt.Button();
        UbahBarang = new java.awt.Button();
        HapusBarang = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        jLabel6.setText("ID :");

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("ID :");

        jTextIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdPelangganActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama :");

        jLabel7.setText("Alamat :");

        jTextAlamatPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlamatPelangganActionPerformed(evt);
            }
        });

        TambahPelanggan.setLabel("Tambah");
        TambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPelangganActionPerformed(evt);
            }
        });

        UbahPelanggan.setLabel("Ubah");
        UbahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPelangganActionPerformed(evt);
            }
        });

        HapusPelanggan.setLabel("Hapus");
        HapusPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPelangganActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UbahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HapusPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextIdPelanggan)
                            .addComponent(jTextAlamatPelanggan)
                            .addComponent(jTextNamaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HapusPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        TambahPelanggan.getAccessibleContext().setAccessibleName("");
        TambahPelanggan.getAccessibleContext().setAccessibleDescription("Tambah");

        jTabbedPane1.addTab("Pelanggan", jPanel1);

        jLabel2.setText("Kode :");

        jLabel8.setText("Nama :");

        jLabel9.setText("Harga :");

        jTextHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHargaBarangActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        TambahBarang.setLabel("Tambah");
        TambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBarangActionPerformed(evt);
            }
        });

        UbahBarang.setLabel("Ubah");

        HapusBarang.setLabel("Hapus");
        HapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UbahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextKodeBarang)
                            .addComponent(jTextHargaBarang)
                            .addComponent(jTextNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel10.setText("Pelanggan :");

        jLabel11.setText("Kasir :");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode Transaksi", "Nama Barang", "Harga Satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Belanja :  RP.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2)
                        .addGap(17, 17, 17))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Transaksi", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1AncestorAdded

    private void HapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusBarangActionPerformed

    private void TambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBarangActionPerformed
        if(jbrg<mbrg){
            //cek kesamaan ID
            boolean ada=false;
            for (int i = 0; i < jbrg; i++) {
                if(brg[i].getKode().equalsIgnoreCase
                    (jTextKodeBarang.getText())){
                    ada=true;
                    break;
                }
            }
            if(ada){
                JOptionPane.showMessageDialog
                (this, "ID sudah ada!");
            }
            else{
                String kd = jTextKodeBarang.getText();
                String nm = jTextNamaBarang.getText();
                String h = jTextHargaBarang.getText();
                brg[jbrg] = new cBarang(nm,kd,h);
                //siapkan array String utk ditampilkan di tabel
                String row[][] = new String[1][3];
                row[0][0] = brg[jbrg].getKode();
                row[0][1] = brg[jbrg].getNama();
                row[0][2] =
                String.valueOf(brg[jbrg].getHarga());
                DefaultTableModel model =
                (DefaultTableModel)jTable2.getModel();
                model.addRow(row[0]);
                jbrg++;
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses...");
                //kosongkan kembali textfield-nya form
                jTextKodeBarang.setText("");
                jTextNamaBarang.setText("");
                jTextHargaBarang.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,
                "Kapasitas penuh!");
            //kosongkan kembali textfield-nya form
            jTextKodeBarang.setText("");
            jTextNamaBarang.setText("");
            jTextHargaBarang.setText("");
        }
    }//GEN-LAST:event_TambahBarangActionPerformed

    private void jTextHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHargaBarangActionPerformed

    private void HapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPelangganActionPerformed
        //cari dulu ID di array object pelanggan
        boolean ketemu=false;
        int indeks=0;
        String id = JOptionPane.showInputDialog(this,
            "Masukkan ID");
        for (int i = 0; i < jplg; i++) {
            indeks=i;
            if(plg[i].getID().equalsIgnoreCase(id)){
                ketemu=true;
                break;
            }
        }
        if(ketemu==true){
            int j = JOptionPane.showConfirmDialog(this,
                "Yakin dihapus?");
            if(j==0){
                for (int i = indeks; i < jplg; i++) {
                    if(i==jplg-1)
                    plg[i] = null;
                    else
                    plg[i]=plg[i+1];
                }
                jplg--;
                //update isi tabel
                DefaultTableModel model =
                (DefaultTableModel)jTable1.getModel();
                model.removeRow(indeks);
                JOptionPane.showMessageDialog(this,
                    "Berhasil dihapus...");
            }
            else JOptionPane.showMessageDialog(this,
                "Batal dihapus!");
        }
        else {
            JOptionPane.showMessageDialog(this, "ID tidak ada!");
        }
    }//GEN-LAST:event_HapusPelangganActionPerformed

    private void UbahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPelangganActionPerformed
        //asumsinya yg berubah adalah data alamat saja
        boolean ketemu=false;
        int indeks=0;
        String id = JOptionPane.showInputDialog(this,
            "Masukkan ID");
        //cek cari dulu ID di array pelanggan
        for (int i = 0; i < jplg; i++) {
            indeks=i;
            if(plg[i].getID().equalsIgnoreCase(id)){
                ketemu=true;
                break;
            }
        }
        if(ketemu==true){
            String al = JOptionPane.showInputDialog(this,
                "Masukkan Alamat Baru");
            int j = JOptionPane.showConfirmDialog(this,
                "Yakin diubah");
            if(j==0){
                plg[indeks].setAlamat(al);
                DefaultTableModel model =
                (DefaultTableModel)jTable1.getModel();
                //update sel baris ke-indeks, kolom ke-2
                model.setValueAt(al, indeks, 2);
                JOptionPane.showMessageDialog(this,
                    "Berhasil diperbarui...");
            }
            else JOptionPane.showMessageDialog
            (this,"Batal Update!");
        }
        else {
            JOptionPane.showMessageDialog
            (this, "ID tidak ada!");
        }
    }//GEN-LAST:event_UbahPelangganActionPerformed

    private void TambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPelangganActionPerformed
        if(jplg<mplg){
            //cek kesamaan ID
            boolean ada=false;
            for (int i = 0; i < jplg; i++) {
                if(plg[i].getID().equalsIgnoreCase
                    (jTextIdPelanggan.getText())){
                    ada=true;
                    break;
                }
            }
            if(ada){
                JOptionPane.showMessageDialog
                (this, "ID sudah ada!");
            }
            else{
                String kd = jTextIdPelanggan.getText();
                String nm = jTextNamaPelanggan.getText();
                String al = jTextAlamatPelanggan.getText();
                plg[jplg] = new cPelanggan(kd,nm,al);
                //siapkan array String utk ditampilkan di tabel
                String row[][] = new String[1][3];
                row[0][0] = plg[jplg].getID();
                row[0][1] = plg[jplg].getNama();
                row[0][2] =
                String.valueOf(plg[jplg].getAlamat());
                DefaultTableModel model =
                (DefaultTableModel)jTable1.getModel();
                model.addRow(row[0]);
                jplg++;
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses...");
                //kosongkan kembali textfield-nya form
                jTextIdPelanggan.setText("");
                jTextNamaPelanggan.setText("");
                jTextAlamatPelanggan.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,
                "Kapasitas penuh!");
            //kosongkan kembali textfield-nya form
            jTextIdPelanggan.setText("");
            jTextNamaPelanggan.setText("");
            jTextAlamatPelanggan.setText("");
        }
    }//GEN-LAST:event_TambahPelangganActionPerformed

    private void jTextAlamatPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlamatPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlamatPelangganActionPerformed

    private void jTextIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdPelangganActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppTokoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppTokoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppTokoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppTokoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppTokoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button HapusBarang;
    private java.awt.Button HapusPelanggan;
    private java.awt.Button TambahBarang;
    private java.awt.Button TambahPelanggan;
    private java.awt.Button UbahBarang;
    private java.awt.Button UbahPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextAlamatPelanggan;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextHargaBarang;
    private javax.swing.JTextField jTextIdPelanggan;
    private javax.swing.JTextField jTextKodeBarang;
    private javax.swing.JTextField jTextNamaBarang;
    private javax.swing.JTextField jTextNamaPelanggan;
    // End of variables declaration//GEN-END:variables
}
